# Generated by Django 4.0.3 on 2022-06-14 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('diary_seq', models.AutoField(primary_key=True, serialize=False)),
                ('diary_title', models.CharField(max_length=64)),
                ('diary_content', models.TextField(max_length=65536)),
                ('diary_img', models.ImageField(upload_to='')),
                ('diary_user_pk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiaryPostLog',
            fields=[
                ('dp_seq', models.AutoField(primary_key=True, serialize=False)),
                ('dp_created', models.DateTimeField(auto_now_add=True)),
                ('dp_updated', models.DateTimeField(auto_now=True)),
                ('dp_diary_pk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diary.diary')),
            ],
        ),
        migrations.CreateModel(
            name='DiaryFileLog',
            fields=[
                ('df_seq', models.AutoField(primary_key=True, serialize=False)),
                ('df_filepath', models.CharField(max_length=256)),
                ('df_filename', models.CharField(max_length=64)),
                ('df_upload_date', models.DateTimeField(auto_now_add=True)),
                ('df_diary_pk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diary.diary')),
            ],
        ),
    ]
